spring:
  application:
    name: spring-cloud-producer
  cloud:
    consul:
      port: 8500
      host: localhost
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
server:
  port: 8081