spring:
  application:
    name: spring-cloud-comsumer
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
      sampler:
        probability: 1.0
      trace-id128: true
server:
  port: 8082
feign:
  hystrix:
    enabled: true